FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG DATABASE_URL
ARG REDIS_URL
ARG GROQ_API_KEY
ARG EMBEDDING_API_URL
ARG EMBEDDING_API_KEY
ARG EMBEDDING_DIMENSIONS

ENV DATABASE_URL=$DATABASE_URL
ENV REDIS_URL=$REDIS_URL
ENV GROQ_API_KEY=$GROQ_API_KEY
ENV EMBEDDING_API_URL=$EMBEDDING_API_URL
ENV EMBEDDING_API_KEY=$EMBEDDING_API_KEY
ENV EMBEDDING_DIMENSIONS=$EMBEDDING_DIMENSIONS

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
