FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG DATABASE_URL
ARG REDIS_URL
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GROQ_API_KEY
ARG EMBEDDING_API_URL
ARG EMBEDDING_API_KEY
ARG EMBEDDING_DIMENSIONS

ENV DATABASE_URL=$DATABASE_URL
ENV REDIS_URL=$REDIS_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GROQ_API_KEY=$GROQ_API_KEY
ENV EMBEDDING_API_URL=$EMBEDDING_API_URL
ENV EMBEDDING_API_KEY=$EMBEDDING_API_KEY
ENV EMBEDDING_DIMENSIONS=$EMBEDDING_DIMENSIONS

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
