apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synapse.fullname" . }}-app
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "synapse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.app.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "synapse.fullname" . }}-env
            {{- if or .Values.secrets.create .Values.secrets.existingSecret }}
            - secretRef:
                name: {{ if .Values.secrets.create }}{{ include "synapse.fullname" . }}-secrets{{ else }}{{ .Values.secrets.existingSecret }}{{ end }}
                optional: true
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
