apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}-app
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP

