{{- if .Values.nginx.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "synapse.fullname" . }}-nginx
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "synapse.fullname" . }}-nginx
  minReplicas: {{ .Values.nginx.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nginx.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nginx.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
