global:
  environment: staging

image:
  repository: 161012475209.dkr.ecr.us-east-1.amazonaws.com/synapse
  tag: latest

app:
  replicaCount: 2

worker:
  replicaCount: 2

nginx:
  replicaCount: 2

ingress:
  hosts:
    - host: staging.synapse.example.com
      paths:
        - path: /
          pathType: Prefix
