global:
  environment: dev

image:
  repository: 161012475209.dkr.ecr.us-east-1.amazonaws.com/synapse
  tag: latest

app:
  replicaCount: 1

worker:
  replicaCount: 1

nginx:
  replicaCount: 1

ingress:
  hosts:
    - host: dev.synapse.example.com
      paths:
        - path: /
          pathType: Prefix
